### ISSUE TITLE
无法解析长文本

### ISSUE THREAD

**Issue by Noogear** [xming-cn/SbPlaceholder-Wiki#1]
![QQ截图20230207070646](https://user-images.githubusercontent.com/123232885/217107599-46bc37bc-94c7-4604-a1c1-5661f034d906.jpg)
如图所示
![QQ截图20230207070722](https://user-images.githubusercontent.com/123232885/217107650-4c7d9eae-b094-40d7-9e0c-fe3b5224e21d.jpg)
无法解析长文本

**Comment by xming-cn** [comment]
你的进度真的很快，马上就要结束了，祝你好运bWdlYWVlXzE1X2ZzdGlhaG4=HEX5845 is big

**Comment by Noogear** [comment]
[07:20:00 警告]: java.lang.IllegalArgumentException: 无法计算: http: / /textures.minecraft.net
[07:20:00 警告]: 	at SbPlaceholder-1.4.0.jar//skyblock.xming.SbParser.handleOperaror(SbParser.java:114)
[07:20:00 警告]: 	at SbPlaceholder-1.4.0.jar//skyblock.xming.SbParser.parseExpression(SbParser.java:527)
[07:20:00 警告]: 	at SbPlaceholder-1.4.0.jar//skyblock.xming.SbParser.parseExpression(SbParser.java:519)
[07:20:00 警告]: 	at SbPlaceholder-1.4.0.jar//skyblock.xming.SbParser.parseExpression(SbParser.java:519)
[07:20:00 警告]: 	at SbPlaceholder-1.4.0.jar//skyblock.xming.SbParser.parse(SbParser.java:39)
[07:20:00 警告]: 	at SbPlaceholder-1.4.0.jar//skyblock.xming.SbPlaceholderExpension.onRequest(SbPlaceholderExpension.java:42)
[07:20:00 警告]: 	at PlaceholderAPI-2.11.2.jar//me.clip.placeholderapi.replacer.CharsReplacer.apply(CharsReplacer.java:119)
[07:20:00 警告]: 	at PlaceholderAPI-2.11.2.jar//me.clip.placeholderapi.PlaceholderAPI.setPlaceholders(PlaceholderAPI.java:71)
[07:20:00 警告]: 	at PlaceholderAPI-2.11.2.jar//me.clip.placeholderapi.PlaceholderAPI.setPlaceholders(PlaceholderAPI.java:99)

**Comment by xming-cn** [comment]
这不是一个错误，而是一个SBP的特性。
SBP会动态的扫描的文本并处理表达式。
即使是占位符返回的链接中的/也会被当做除号处理。

但无论如何，这是一个值得引起关注的问题。
我会尝试为这种情况提供解决方案。
